package CalcOp;


/**
* CalcOp/Calc.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalcOp.idl
* Wednesday, 7 May, 2025 4:53:23 PM IST
*/

public interface Calc extends CalcOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calc
