package MathsOp;

/**
* MathsOp/MathsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MathsOp.idl
* Wednesday, 7 May, 2025 4:15:27 PM IST
*/

public final class MathsHolder implements org.omg.CORBA.portable.Streamable
{
  public MathsOp.Maths value = null;

  public MathsHolder ()
  {
  }

  public MathsHolder (MathsOp.Maths initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MathsOp.MathsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MathsOp.MathsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MathsOp.MathsHelper.type ();
  }

}
