package MathsOp;


/**
* MathsOp/Maths.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MathsOp.idl
* Wednesday, 7 May, 2025 4:15:27 PM IST
*/

public interface Maths extends MathsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Maths
