package CalculatorApp;


/**
* CalculatorApp/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Monday, 10 February, 2025 10:01:27 PM IST
*/

public interface CalculatorOperations 
{
  double add (double a, double b);
  double subtract (double a, double b);
  double multiply (double a, double b);
  double divide (double a, double b);
} // interface CalculatorOperations
