package PallindromeString;


/**
* PallindromeString/Pallindrome.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PallindromeString.idl
* Monday, 10 February, 2025 11:00:27 PM IST
*/

public interface Pallindrome extends PallindromeOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Pallindrome
