package PallindromeString;


/**
* PallindromeString/PallindromeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PallindromeString.idl
* Monday, 10 February, 2025 11:00:27 PM IST
*/

public interface PallindromeOperations 
{
  boolean isPallindrome (String str);
} // interface PallindromeOperations
