package PallindromeString;


/**
* PallindromeString/PallindromePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PallindromeString.idl
* Monday, 10 February, 2025 11:00:27 PM IST
*/

public abstract class PallindromePOA extends org.omg.PortableServer.Servant
 implements PallindromeString.PallindromeOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("isPallindrome", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // PallindromeString/Pallindrome/isPallindrome
       {
         String str = in.read_string ();
         boolean $result = false;
         $result = this.isPallindrome (str);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:PallindromeString/Pallindrome:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Pallindrome _this() 
  {
    return PallindromeHelper.narrow(
    super._this_object());
  }

  public Pallindrome _this(org.omg.CORBA.ORB orb) 
  {
    return PallindromeHelper.narrow(
    super._this_object(orb));
  }


} // class PallindromePOA
