package PallindromeString;


/**
* PallindromeString/PallindromeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PallindromeString.idl
* Monday, 10 February, 2025 11:00:27 PM IST
*/

abstract public class PallindromeHelper
{
  private static String  _id = "IDL:PallindromeString/Pallindrome:1.0";

  public static void insert (org.omg.CORBA.Any a, PallindromeString.Pallindrome that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static PallindromeString.Pallindrome extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (PallindromeString.PallindromeHelper.id (), "Pallindrome");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static PallindromeString.Pallindrome read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_PallindromeStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, PallindromeString.Pallindrome value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static PallindromeString.Pallindrome narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof PallindromeString.Pallindrome)
      return (PallindromeString.Pallindrome)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      PallindromeString._PallindromeStub stub = new PallindromeString._PallindromeStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static PallindromeString.Pallindrome unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof PallindromeString.Pallindrome)
      return (PallindromeString.Pallindrome)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      PallindromeString._PallindromeStub stub = new PallindromeString._PallindromeStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
