package CalculatorAdd;


/**
* CalculatorAdd/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalculatorAdd.idl
* Wednesday, 7 May, 2025 3:09:22 PM IST
*/

public interface CalculatorOperations 
{
  double add (double a, double b);
} // interface CalculatorOperations
