package CalculatorOp;


/**
* CalculatorOp/Calculator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalculatorOp.idl
* Wednesday, 7 May, 2025 3:33:41 PM IST
*/

public interface Calculator extends CalculatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calculator
